docs: add the docs to commitlint

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,1 +1,15 @@
-npx  commitlint --edit "$1"
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+echo "\033[1;36m📝 Checking commit message with the conventions of the @commitlint/config-conventional ...\033[0m"
+
+npx commitlint --edit "$1"
+status=$?
+
+if [ $status -ne 0 ]; then
+  echo "\033[1;31m❌ Commit message is invalid! Use format: <type>(scope): message\033[0m"
+  echo "\033[1;33m🔗 Example: feat(auth): add login feature\033[0m"
+  exit 1
+else
+  echo "\033[1;32m✅ excellent , Commit message is valid!\033[0m"
+fi
diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,11 @@
-lint-staged
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+echo "\033[1;36m🔍 Running Pre-commit Checks, i hope u can pass this step...\033[0m"
+
+npx lint-staged || {
+  echo "\033[1;31m❌ I am sorry you have issues here . Linting failed. Please fix the errors before committing.\033[0m"
+  exit 1
+}
+
+echo "\033[1;32m✅ All lint checks passed!\033[0m"
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,17 @@
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+echo "\033[1;36m🚀 Running Pre-push Checks...\033[0m"
+
+echo "\033[1;34m📦 Checking build...\033[0m"
 
 
-npm run build 
+npm run build --if-present
+BUILD_EXIT_CODE=$?
 
+if [ $BUILD_EXIT_CODE -ne 0 ]
+  echo "\033[1;31m❌ Build failed! Push aborted.\033[0m"
+  exit 1
+fi
+
+echo "\033[1;32m✅ Pre-push checks passed. Proceeding with push...\033[0m"
